version: "3"
services:
  database:
    container_name: wanted_db
    image: mysql:8.0.32
    environment:
      MYSQL_DATABASE: wanted_db
      MYSQL_ROOT_PASSWORD: 1234
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
  application:
    container_name: wanted_app
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/wanted_db?characterEncoding=UTF-8&serverTimezone=UTC&&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - database